workflows:
  build_flutter_app:  # Replace with a descriptive name if needed
    name: Build Flutter App (Internal Distribution)
    instance_type: runner_m  # Adjust if needed based on resource requirements
    environment:
      # Add environment variables if needed for your build process

    cache:
      paths:
        - pubspec.lock
        - '**/.pub'

    triggering:
      events:
        - push  # Trigger workflow on push events (code updates)

    scripts:
      - name: Checkout code
        command: git clone https://your-git-repository.git  # Replace with your repo URL
      - name: Install dependencies
        command: flutter pub get
      - name: Build app (release mode)
        command: flutter build appbundle --release
      # Add additional scripts for testing or signing if needed
      - name: (Optional) Download build artifact (placeholder)
        command: # Replace with commands to download the built app (.aab file)

    artifacts:
      - paths:
          - build/app/outputs/flutter-apk/app-release.aab  # Update path if different
